/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ryzen.gltf 
Author: Piekub.Nakub (https://sketchfab.com/Piekub.Nakub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/amd-cpu-am4-ryzen-5-pro-4650g-next-37-ghz-c4fc68b00689405f99cfebc87107a141
Title: AMD CPU AM4 RYZEN 5 Pro 4650G (NEXT) 3.7 GHz
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ryzen.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.075, 0, -0.162]}>
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_1} />
      </group>
      <group position={[0, 0, -0.013]}>
        <group position={[0.075, 0, -0.162]} rotation={[0.129, -0.624, 0.076]}>
          <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.material_4} />
        </group>
      </group>
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_2} />
    </group>
  )
}

useGLTF.preload('/ryzen.gltf')
